[variables]
NIXPACKS_NODE_VERSION = "20"
NODE_OPTIONS = "--max-old-space-size=4096"

[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm", "python3", "gnumake", "gcc", "g++"]

[phases.install]
cmds = ["echo '--- STARTING CUSTOM PNPM INSTALL ---'", "pnpm install --frozen-lockfile --prefer-offline"]

[phases.build]
cmds = ["pnpm run build"]
