[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs-20_x", "python3", "gnumake", "gcc", "g++"]

[phases.install]
cmds = ["yarn install --production=false"]

[phases.build]
cmds = ["yarn run build"]
